# Generated by Django 5.0.6 on 2024-05-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'book_author',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'book_category',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.TextField()),
                ('star_given', models.IntegerField()),
            ],
            options={
                'db_table': 'book_review',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('page', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='media/default_img/default_book_img.jpg', upload_to='book/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bookcategory')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='author_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.review'),
        ),
    ]
